name: Release iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS production app
    type: build
    params:
      platform: ios
      profile: production

  submit_ios:
    name: Submit to TestFlight
    needs: [build_ios]
    type: testflight
    params:
      build_id: ${{ needs.build_ios.outputs.build_id }}
